[container:home-links]
[container:home-links-left]
[container:home-linkblock]
[h2]Characters[/h2]
[h4]Factions[/h4]
[url:/generia/stats/characters/factions/bandits]Bandits[/url]
[br][url:/generia/stats/characters/factions/bloody-hand]Bloody Hand[/url]
[br][url:/generia/stats/characters/factions/guard]Guard[/url]
[br][url:/generia/stats/characters/factions/horde]Horde[/url]
[br][url:/generia/stats/characters/factions/nergadai]Nergadai[/url]
[h4]Templates[/h4]
[url:/generia/stats/characters/templates/_level-7]Level 7[/url]
[br][url:/generia/stats/characters/templates/archer-templates]Archer[/url]
[br][url:/generia/stats/characters/templates/bard-templates]Bard[/url]
[br][url:/generia/stats/characters/templates/berserker-templates]Berserker[/url]
[br][url:/generia/stats/characters/templates/druid-templates]Druid[/url]
[br][url:/generia/stats/characters/templates/fighter-templates]Fighter[/url]
[br][url:/generia/stats/characters/templates/nox-templates]Nox[/url]
[br][url:/generia/stats/characters/templates/shaman-templates]Shaman[/url]
[br][url:/generia/stats/characters/templates/wizard-templates]Wizard[/url]
[/container]
[/container]


[container:home-links-right]
[container:home-linkblock]
[h2]Creatures[/h2]
[h4]Humanoids[/h4]
[url:/generia/stats/creatures/humanoids/gnolls]Gnolls[/url]
[br][url:/generia/stats/creatures/humanoids/goblins]Goblins[/url]
[br][url:/generia/stats/creatures/humanoids/ogres]Ogres[/url]
[br][url:/generia/stats/creatures/humanoids/trolls]Trolls[/url]
[h4]Fey[/h4]
[url:/generia/stats/creatures/fey/pixies]Pixies[/url]
[h4]Insectoids[/h4]
[url:/generia/stats/creatures/insectoids/krii]Krii[/url]
[h4]Dracids[/h4]
[url:/generia/stats/creatures/dracids/wyverns]Wyverns[/url]
[h4]Morphids[/h4]
[url:/generia/stats/creatures/oddities/morphids]Morphids[/url]
[h4]Beasts[/h4]
[url:/generia/stats/creatures/beasts/beasts-mundane]Mundane[/url]
[br][url:/generia/stats/creatures/beasts/beasts-rift]Rift[/url]
[br][url:/generia/stats/creatures/beasts/beasts-deep-wilds]Deep Wilds[/url]
[h4]Elementals[/h4]
[url:/generia/stats/creatures/elementals/elementals-lesser]Lesser[/url], [url:/generia/stats/creatures/elementals/elementals-normal]Normal[/url], [url:/generia/stats/creatures/elementals/elementals-greater]Greater[/url]
[br][url:/generia/stats/creatures/elementals/elementals-water]Water[/url], [url:/generia/stats/creatures/elementals/elementals-stone]Stone[/url], [url:/generia/stats/creatures/elementals/elementals-fire]Fire[/url], [url:/generia/stats/creatures/elementals/elementals-air]Air[/url]
[h4]Void[/h4]
[url:/generia/stats/creatures/void/skeletons]Skeletons[/url]
[/container]
[/container]
[/container]