[container:home-links]

[container:home-links-left]
[container:home-linkblock]
[h2]Brandt Family[/h2]
[url:/generia/stats/characters/_story/brandt/daniel-brandt]Daniel[/url]
[br][url:/generia/stats/characters/_story/brandt/kai-brandt]Kai[/url]
[br][url:/generia/stats/characters/_story/brandt/laura-brandt]Laura[/url]
[br][url:/generia/stats/characters/_story/brandt/lena-brandt]Lena[/url]
[h2]Lindenfeld: Vanguard[/h2]
[url:/generia/stats/characters/_story/lindenfeld/vanguard/marie-neumann]Marie[/url]
[br][url:/generia/stats/characters/_story/lindenfeld/vanguard/alexander-walters]Alexander[/url]
[/container]
[container:home-linkblock]
[h2]Sneaky Bastard[/h2]
[url:/generia/stats/characters/_story/_sneaky-bastard/lukas-faber]Lukas (Shade)[/url]
[/container]
[/container]


[container:home-links-right]
[container:home-linkblock]
[h2]TH – Public[/h2]
[url:/generia/stats/characters/_story/_public/ch3]Chapter 3[/url]
[br][url:/generia/stats/characters/_story/_public/ch4]Chapter 4[/url]
[br][url:/generia/stats/characters/_story/_public/ch11]Chapter 11[/url]
[br][url:/generia/stats/characters/_story/_public/th/th-ch16]Chapter 16[/url]
[br][url:/generia/stats/characters/_story/_public/ch23]Chapter 23[/url]
[br][url:/generia/stats/characters/_story/_public/ch32]Chapter 32[/url]
[/container]
[container:home-linkblock]
[h2]SB – Public[/h2]
[url:/generia/stats/characters/_story/_public/sb/ch2]Chapter 2[/url]
[br][url:/generia/stats/characters/_story/_public/sb/ch4]Chapter 4[/url]
[br][url:/generia/stats/characters/_story/_public/sb/ch6]Chapter 6[/url]
[br][url:/generia/stats/characters/_story/_public/sb/ch12]Chapter 12[/url]
[br][url:/generia/stats/characters/_story/_public/sb/ch15]Chapter 15[/url]
[br][url:/generia/stats/characters/_story/_public/sb/ch23]Chapter 23[/url]
[/container]
[/container]

[/container]