[h2]Description[/h2]
Wayfarer
[h4]Prerequisites[/h4]
[url:class2/class-monk]Monk[/url]
[h4]Subclasses[/h4]
–

[h2]Abilities[/h2]
[h4]Perks – Combat[/h4]
[ul]
[li][url:perksC#Deflector]Deflector[/url][/li]
[/ul]
[h4]Perks – Magic[/h4]
[ul]
[li][/li]
[/ul]
[h4]Weapons[/h4]
[ul]
[li][b]Natural Weapons: Adept [i](30 SP)[/i][/b][/li]
[/ul]
[h4]Skills[/h4]
[ul]
[li][/li]
[/ul]
[h4]Spells[/h4]
[ul]
[li][/li]
[/ul]