[container:home-links]
[container:home-links-left]
[container:home-linkblock]
[h2]Characters[/h2]
[h4]Factions[/h4]
[url:/generia/stats/characters/factions/bandits/bandits-10]Bandits 10[/url], [url:/generia/stats/characters/factions/bandits/bandits-15]Bandits 15[/url], [url:/generia/stats/characters/factions/bandits/bandits-20]Bandits 20[/url]
[br][url:/generia/stats/characters/factions/bloody-hand/bloody-hand-20]Bloody Hand 20[/url], [url:/generia/stats/characters/factions/bloody-hand/bloody-hand-25]Bloody Hand 25[/url]
[br][url:/generia/stats/characters/factions/guard/guard-15]Guard 15[/url]
[br][url:/generia/stats/characters/factions/horde/horde-20]Horde 20[/url]
[h4]Templates[/h4]
[url:/generia/stats/characters/templates/_level-7]Level 7[/url]
[br][url:/generia/stats/characters/templates/archer-templates]Archer[/url]
[br][url:/generia/stats/characters/templates/bard-templates]Bard[/url]
[br][url:/generia/stats/characters/templates/Berserker-templates]Berserker[/url]
[br][url:/generia/stats/characters/templates/druid-templates]Druid[/url]
[br][url:/generia/stats/characters/templates/fighter-templates]Fighter[/url]
[br][url:/generia/stats/characters/templates/nox-templates]Nox[/url]
[br][url:/generia/stats/characters/templates/shaman-templates]Shaman[/url]
[br][url:/generia/stats/characters/templates/wizard-templates]Wizard[/url]
[/container]
[/container]


[container:home-links-right]
[container:home-linkblock]
[h2]Creatures[/h2]
[h4]Humanoids[/h4]

[h4]Dracids[/h4]

[h4]Beasts[/h4]
[url:/generia/stats/creatures/beasts/rift-beasts]Rift Beasts[/url]
[/container]
[/container]
[/container]