[container:home-links]
[container:home-links-left]
[container:home-linkblock]
[h2]Player Characters[/h2]
[url:/generia/stats/characters/_player/gavins-party-stats]Gavin's Party[/url]
[br][url:/generia/stats/characters/_player/karim-minu]Karim & Minu[/url]
[/container]
[/container]


[container:home-links-right]
[container:home-linkblock]
[h2]Pets & Summons[/h2]
[url:/generia/stats/characters/_player/cassandra-pets]Cassandra[/url]
[br][url:/generia/stats/characters/_player/zedrow-pets]Zedrow[/url]
[/container]
[/container]
[/container]