[container:home-links]
[container:home-links-left]
[container:home-linkblock]
[h2]Brandt Family[/h2]
[url:/generia/stats/characters/_story/brandt/kai-brandt]Kai[/url]
[br][url:/generia/stats/characters/_story/brandt/laura-brandt]Laura[/url]
[br][url:/generia/stats/characters/_story/brandt/lena-brandt]Lena[/url]
[h2]Lindenfeld: Vanguard[/h2]
[url:/generia/stats/characters/_story/lindenfeld/vanguard/marie-neumann]Marie[/url]
[br][url:/generia/stats/characters/_story/lindenfeld/vanguard/alexander-walters]Alexander[/url]
[/container]
[/container]


[container:home-links-right]
[container:home-linkblock]
[h2]Public[/h2]
[url:/generia/stats/characters/_story/_public/ch3]Chapter 3[/url]
[br][url:/generia/stats/characters/_story/_public/ch4]Chapter 4[/url]
[br][url:/generia/stats/characters/_story/_public/ch11]Chapter 11[/url]
[br][url:/generia/stats/characters/_story/_public/ch16]Chapter 16[/url]
[br][url:/generia/stats/characters/_story/_public/ch23]Chapter 23[/url]
[/container]
[/container]
[/container]